import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Brain, Loader2, X, FileText, Download, CheckCircle2, AlertCircle, ListChecks, BarChart3 } from "lucide-react";
import { prepareMeeting } from "@/lib/api";
import type { MeetingReport } from "@/lib/types";
import { downloadFile } from "@/lib/utils";

export function MeetingMode({ onClose }: { onClose: () => void }) {
  const [report, setReport] = useState<MeetingReport | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    prepareMeeting()
      .then(setReport)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const exportPdf = () => {
    if (!report) return;
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Executive Meeting Report</title>
<style>body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:20px;color:#1a1a2e;line-height:1.6}
h1{color:#4338ca;border-bottom:3px solid #6366f1;padding-bottom:10px}h2{color:#3730a3;margin-top:24px}
ul{padding-left:20px}.kpi{display:inline-block;margin:8px;padding:8px 16px;background:#eef2ff;border-radius:8px}
.footer{margin-top:40px;padding-top:12px;border-top:1px solid #ddd;font-size:11px;color:#999}</style></head><body>
<h1>Executive Meeting Report</h1>
<h2>Agenda</h2><ul>${report.agenda.map(a => `<li>${a}</li>`).join("")}</ul>
<h2>Executive Summary</h2><p>${report.executiveSummary}</p>
<h2>Talking Points</h2><ul>${report.talkingPoints.map(t => `<li>${t}</li>`).join("")}</ul>
<h2>Key KPIs</h2>${report.keyKpis.map(k => `<div class="kpi"><strong>${k.label}:</strong> ${k.value}</div>`).join("")}
<h2>Business Concerns</h2><ul>${report.concerns.map(c => `<li>${c}</li>`).join("")}</ul>
<h2>Recommendations</h2><ul>${report.recommendations.map(r => `<li>${r}</li>`).join("")}</ul>
<div class="footer">Generated by QueryMind AI Analytics Platform</div></body></html>`;
    const w = window.open(URL.createObjectURL(new Blob([html], { type: "text/html" })), "_blank");
    if (w) w.onload = () => setTimeout(() => w.print(), 500);
  };

  const exportText = () => {
    if (!report) return;
    const text = [
      "EXECUTIVE MEETING REPORT", "=".repeat(50), "",
      "AGENDA", "-".repeat(20), report.agenda.map(a => `  ${a}`).join("\n"), "",
      "EXECUTIVE SUMMARY", "-".repeat(20), report.executiveSummary, "",
      "TALKING POINTS", "-".repeat(20), report.talkingPoints.map(t => `  - ${t}`).join("\n"), "",
      "KEY KPIs", "-".repeat(20), report.keyKpis.map(k => `  ${k.label}: ${k.value}`).join("\n"), "",
      "BUSINESS CONCERNS", "-".repeat(20), report.concerns.map(c => `  - ${c}`).join("\n"), "",
      "RECOMMENDATIONS", "-".repeat(20), report.recommendations.map(r => `  - ${r}`).join("\n"), "",
      "=".repeat(50), "Generated by QueryMind AI Analytics Platform",
    ].join("\n");
    downloadFile("querymind-meeting-report.txt", text, "text/plain");
  };

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
        onClick={(e) => e.stopPropagation()}
        className="glass-card w-full max-w-2xl max-h-[88vh] overflow-y-auto scrollbar-thin"
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-white/5 sticky top-0 bg-slate-900/80 backdrop-blur-xl z-10">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 shadow-lg">
              <Brain className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-bold gradient-text">AI Meeting Mode</h2>
              <p className="text-xs text-slate-500">Executive meeting preparation</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {report && (
              <>
                <button onClick={exportPdf} className="flex items-center gap-1.5 rounded-lg bg-sky-500/15 border border-sky-500/30 px-3 py-1.5 text-xs text-sky-300 hover:bg-sky-500/25 transition-colors">
                  <Download className="h-3.5 w-3.5" /> PDF
                </button>
                <button onClick={exportText} className="flex items-center gap-1.5 rounded-lg bg-white/5 border border-white/10 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/10 transition-colors">
                  <Download className="h-3.5 w-3.5" /> Text
                </button>
              </>
            )}
            <button onClick={onClose} className="text-slate-400 hover:text-slate-200"><X className="h-5 w-5" /></button>
          </div>
        </div>

        <div className="p-5">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-6 w-6 text-violet-400 animate-spin" />
              <span className="ml-2 text-sm text-slate-400">Preparing executive meeting...</span>
            </div>
          ) : report ? (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
              <Section icon={ListChecks} label="Agenda" color="text-sky-400">
                <ul className="space-y-1">{report.agenda.map((a, i) => <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5"><span className="text-slate-600 mt-0.5">•</span>{a}</li>)}</ul>
              </Section>
              <Section icon={FileText} label="Executive Summary" color="text-violet-400">
                <p className="text-sm text-slate-300 leading-relaxed">{report.executiveSummary}</p>
              </Section>
              <Section icon={Brain} label="Talking Points" color="text-emerald-400">
                <ul className="space-y-1">{report.talkingPoints.map((t, i) => <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5"><span className="text-emerald-400 mt-0.5">•</span>{t}</li>)}</ul>
              </Section>
              <Section icon={BarChart3} label="Key KPIs" color="text-amber-400">
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {report.keyKpis.map((k, i) => (
                    <div key={i} className="rounded-lg bg-white/[0.03] border border-white/5 px-3 py-2">
                      <p className="text-[10px] text-slate-500">{k.label}</p>
                      <p className="text-sm font-semibold text-slate-200">{k.value}</p>
                    </div>
                  ))}
                </div>
              </Section>
              <Section icon={AlertCircle} label="Business Concerns" color="text-rose-400">
                <ul className="space-y-1">{report.concerns.map((c, i) => <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5"><span className="text-rose-400 mt-0.5">•</span>{c}</li>)}</ul>
              </Section>
              <Section icon={CheckCircle2} label="Recommendations" color="text-teal-400">
                <ul className="space-y-1">{report.recommendations.map((r, i) => <li key={i} className="text-xs text-slate-400 flex items-start gap-1.5"><span className="text-teal-400 mt-0.5">•</span>{r}</li>)}</ul>
              </Section>
            </motion.div>
          ) : null}
        </div>
      </motion.div>
    </motion.div>
  );
}

function Section({ icon: Icon, label, color, children }: { icon: typeof FileText; label: string; color: string; children: React.ReactNode }) {
  return (
    <div className="glass-card p-4">
      <div className="flex items-center gap-1.5 mb-2">
        <Icon className={`h-4 w-4 ${color}`} />
        <span className="text-sm font-semibold text-slate-200">{label}</span>
      </div>
      {children}
    </div>
  );
}
