import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Loader2, X, ChevronLeft, ChevronRight, Download, FileBarChart } from "lucide-react";
import { generatePresentation } from "@/lib/api";
import type { Presentation } from "@/lib/types";
import { downloadFile } from "@/lib/utils";

export function PresentationGenerator({ onClose }: { onClose: () => void }) {
  const [data, setData] = useState<Presentation | null>(null);
  const [loading, setLoading] = useState(true);
  const [slide, setSlide] = useState(0);

  useEffect(() => {
    generatePresentation()
      .then(setData)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const exportText = () => {
    if (!data) return;
    const text = [
      data.title, "=".repeat(50), "",
      ...data.slides.map((s, i) => [
        `SLIDE ${i + 1}: ${s.title}`, "-".repeat(20),
        s.content, "",
        ...s.bullets.map(b => `  • ${b}`),
        "",
        `Speaker Notes: ${data.speakerNotes[i] ?? ""}`,
        "",
      ].join("\n")),
      "=".repeat(50), "Generated by QueryMind AI Analytics Platform",
    ].join("\n");
    downloadFile("querymind-presentation.txt", text, "text/plain");
  };

  const currentSlide = data?.slides[slide];

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
        onClick={(e) => e.stopPropagation()}
        className="glass-card w-full max-w-3xl max-h-[88vh] overflow-hidden flex flex-col"
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-white/5">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-rose-500 to-pink-600 shadow-lg">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-bold gradient-text">AI Presentation Generator</h2>
              <p className="text-xs text-slate-500">{data?.title ?? "Board Presentation"}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {data && (
              <button onClick={exportText} className="flex items-center gap-1.5 rounded-lg bg-white/5 border border-white/10 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/10 transition-colors">
                <Download className="h-3.5 w-3.5" /> Export
              </button>
            )}
            <button onClick={onClose} className="text-slate-400 hover:text-slate-200"><X className="h-5 w-5" /></button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto scrollbar-thin p-5">
          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="h-8 w-8 text-rose-400 animate-spin" />
              <span className="ml-2 text-sm text-slate-400">Generating presentation slides...</span>
            </div>
          ) : data && currentSlide ? (
            <div>
              {/* Slide */}
              <AnimatePresence mode="wait">
                <motion.div
                  key={slide}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="glass-card p-8 min-h-[320px] flex flex-col"
                >
                  <div className="flex items-center gap-2 mb-4">
                    <FileBarChart className="h-5 w-5 text-rose-400" />
                    <span className="text-xs text-slate-500">Slide {slide + 1} of {data.slides.length}</span>
                  </div>
                  <h3 className="text-2xl font-bold text-slate-100 mb-3">{currentSlide.title}</h3>
                  <p className="text-sm text-slate-400 mb-4 leading-relaxed">{currentSlide.content}</p>
                  <ul className="space-y-2">
                    {currentSlide.bullets.map((b, i) => (
                      <motion.li
                        key={i}
                        initial={{ opacity: 0, x: -8 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.08 }}
                        className="flex items-start gap-2 text-sm text-slate-300"
                      >
                        <span className="text-rose-400 mt-1">•</span>{b}
                      </motion.li>
                    ))}
                  </ul>
                  {currentSlide.chartType && (
                    <div className="mt-4 flex items-center gap-1.5 text-xs text-slate-500">
                      <FileBarChart className="h-3.5 w-3.5" />
                      Chart: {currentSlide.chartType}
                    </div>
                  )}
                </motion.div>
              </AnimatePresence>

              {/* Speaker Notes */}
              <div className="mt-3 rounded-lg bg-violet-500/5 border border-violet-500/10 px-4 py-3">
                <p className="text-xs font-semibold text-violet-400 mb-1">Speaker Notes</p>
                <p className="text-xs text-slate-400 leading-relaxed">{data.speakerNotes[slide]}</p>
              </div>

              {/* Navigation */}
              <div className="flex items-center justify-between mt-4">
                <button
                  onClick={() => setSlide(s => Math.max(0, s - 1))}
                  disabled={slide === 0}
                  className="flex items-center gap-1 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-xs text-slate-300 disabled:opacity-30 hover:bg-white/10 transition-colors"
                >
                  <ChevronLeft className="h-4 w-4" /> Previous
                </button>
                <div className="flex gap-1">
                  {data.slides.map((_, i) => (
                    <button
                      key={i}
                      onClick={() => setSlide(i)}
                      className={`h-2 rounded-full transition-all ${i === slide ? "w-6 bg-rose-400" : "w-2 bg-white/20"}`}
                    />
                  ))}
                </div>
                <button
                  onClick={() => setSlide(s => Math.min(data.slides.length - 1, s + 1))}
                  disabled={slide === data.slides.length - 1}
                  className="flex items-center gap-1 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-xs text-slate-300 disabled:opacity-30 hover:bg-white/10 transition-colors"
                >
                  Next <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            </div>
          ) : null}
        </div>
      </motion.div>
    </motion.div>
  );
}
